apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-frontend
  labels:
    tier: frontend
    app: httpd-frontend
spec:
  selector:
    matchLabels:
      app: httpd-frontend
  replicas: 3
  template:
    metadata:
      name: httpd-frontend
      labels:
        app: httpd-frontend
    spec:
      containers:
        - name: httpd 
          image: httpd:2.4-alpine