apiVersion: v1
kind: Pod
metadata:
  name: tortoise
  labels:
    app: nginx
    tier: frontend
spec:
  containers:
  - name: aldabra-giant
    image: nginx
  - name: galapagos-giant
    image: busybox